name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - workflow-test
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: bahmutov/npm-install@v1
        with:
          node-version: 18

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies with Yarn
        working-directory: ./client
        run:
          npm t
        working-directory: ./server
        run:
          npm t

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
