name: Node.js test

on:
  push:
    paths:
      - 'server/**.ts'
      - '!server/node_modules/**'
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: Run test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      # set up runner with environment
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      # run jest tests 
      - run: npm test