on: [push, pull_request]

jobs:
  nim-test:
    name: Run Nim tests using `nimble test`

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-12]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v4.1.3
        with:
          github_token: ${{ secrets.github_token }}
      - run: nimble install -y
      - run: nimble test

  nim-lint:
    name: Lint Nim code

    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-12]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-nimlint@v1.5.1
        with:
          github_token: ${{ secrets.github_token }}
          src: 'src/*.nim'
